### ISSUE TITLE
Verify Diego/CF deployment

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#183]
## Acceptance Criteria

- [x] Ensure smoke tests use the Diego backend and succeed
- [x] Ensure the acceptance tests use the Diego backend and succeed 🚫 👀  #202 
- [x] Review all platform logs for errors ⛔ 👀 18F/cg-atlas#111
    - [x] On all CF and Diego hosts, review all logs in /var/vcap/sys/log
    - [x] Ensure all component logs are available in the ELK deployment
- [x] Deploy a sample app, verify it's using Diego, and SSH into the container
    - [x] Trace the application end-to-end by its uuid through CF/Diego
- [x] Confirm add-on releases are running on each Diego component (#158)
- [x] Confirm configurations/entities in the dependent systems themselves
    - [x] metrics.fr.cloud.gov 👀 #220 
    - [x] awslogs
    - [x] logs.fr.cloud.gov
    - [x] Nessus
    - [x] New Relic
    - [x] Admin UI (?)
- [x] Verify secrets for Diego

**Comment by sushiandbeer** [comment]
#158 was to confirm all add-ons existed on the Diego components.  I referenced it in the AC above.

**Comment by rogeruiz** [comment]
We're encountering an issue with Metrics, moving the database fixes some of the issues but we're not seeing data coming from InfluxDB.

**Comment by rogeruiz** [comment]
Looks like this is currently blocked until we see a new stemcell that works with `garden-linux` for Diego.
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/PQGMSHFBPDSKEFBI233JX3OETDILYJMS/

This issue came up because of the stemcell upgrade here
18F/cg-atlas#142

**Comment by sushiandbeer** [comment]
awslogs, Nessus, New Relic, Admin UI confirmation tasks need to be performed by someone with login/admin privileges.

**Comment by sushiandbeer** [comment]
Blocked waiting on https://github.com/18F/cg-product/issues/220 and for someone with Nessus access to confirm data there.

**Comment by mogul** [comment]
Seems lightweight; just verify that Diego-specific things are showing up in the right places, but we need to make sure the assignees can actually access those places.

**Comment by cnelson** [comment]
I see logs from diego apps in `logs.fr.cloud.gov`

![image](https://cloud.githubusercontent.com/assets/604163/18973738/ea8af3a2-8653-11e6-9153-bb85a2525a29.png)

**Comment by cnelson** [comment]
I'm calling Nessus done because @dlapiduz [says the diego boxes are in there](https://18f.slack.com/archives/cloud-gov-atlas/p1475189564002020).

**Comment by cnelson** [comment]
We can now see diego cells in admin-ui. 
![image](https://cloud.githubusercontent.com/assets/604163/19002006/ceced9a2-86fe-11e6-9772-d4db3599ab00.png)

I think this issue is as done as it can be until #220 is taken care of.

**Comment by datn** [comment]
We confirmed that there is a diego dashboard with data in it. I checked all the ACs -- I think we're good to go.
![screen shot 2016-09-30 at 12 17 59](https://cloud.githubusercontent.com/assets/928964/19003957/10c55026-8708-11e6-8fb7-a8ea1feba0b0.png)
