### ISSUE TITLE
shibboleth can be deployed with BOSH

### ISSUE THREAD

**Issue by LinuxBozo** [18F/cg-product#248]
In order for the team to be able to configure and scale installations of shibboleth for IdP integration, it should be managed and deployed with BOSH.

**Acceptance Criteria**

* [x] A non-hand-propped Shibboleth exists in AWS, deployed with BOSH
* [x] Existing hand-generated configuration for integration with UAA is incorporated into a pipeline

**Comment by mogul** [comment]
(Moved to `In Progress` as I'm seeing mention of this happening in stand-ups.)

**Comment by rogeruiz** [comment]
@jbarnicle will be looking at this and making sure we can templating this better.

**Comment by rogeruiz** [comment]
- [x] Bosh set up in 18F/shibboleth-boshrelease#1
    - [x] Pipeline set up in 18F/shibboleth-boshrelease#2
- [ ] Deployment Pipeline set up in 18F/cg-deploy-shibboleth/#1

**Comment by rogeruiz** [comment]
Connecting the CF deployment to Shibboleth should be the last thing here.

**Comment by rogeruiz** [comment]
We'll need to update the ELBs for shibboleth to point to port `80` instead of `8080`, eventually.

**Comment by rogeruiz** [comment]
This just needs to be verified by someone who didn't work on it. The pipeline, secrets, etc are all where they should be.
