### ISSUE TITLE
Concourse should return secure HTTP headers

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#469]
In order to be in compliance with best practice security guidelines I want this application to send the appropriate HTTP headers.

**Acceptance Criteria**
- [ ] Cookies should be set with [secure](https://github.com/18F/cg-product/issues/443) and [HttpOnly](https://github.com/18F/cg-product/issues/442) flags where appropriate 
- [ ] Include a [X-XSS-Protection: 1; mode=block](https://github.com/18F/cg-product/issues/439) header in responses
- [ ] Include a ["Cache-Control" header with "no-cache, no-store, must-revalidate, private" and "Pragma: no-cache" header](https://github.com/18F/cg-product/issues/441) where appropriate

**Comment by cnelson** [comment]
Referencing @jmcarp's PR for the cookie part of this so we have it for posterity: https://github.com/concourse/atc/pull/138

**Comment by cnelson** [comment]
@jmcarp @jbarnicle I'm writing our POAM responses right now, what's the status of the  `X-XSS-Protection` header change?

**Comment by jbarnicle** [comment]
@cnelson I opened an issue in the ATC repo to gauge how receptive they would be to accepting a code change / suggested implementation for the `X-XSS-Protection` header.  They asked for more information as to why these settings would be best practice.  I am writing a response that suggests they be configurable to account for various compliance needs.

https://github.com/concourse/atc/issues/144

**Comment by cnelson** [comment]
This is also blocked on the fact that Pivotal is requiring a CLA for Concourse contributors which cannot be executed by 18F in it's current state.  @NoahKunin has opened a discussion with Pivotal about this.
