### ISSUE TITLE
Metrics should return secure HTTP headers

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#472]
In order to be in compliance with best practice security guidelines I want this application to send the appropriate HTTP headers.

**Acceptance Criteria**
- [x] Cookies should be set with [secure](https://github.com/18F/cg-product/issues/443) and [HttpOnly](https://github.com/18F/cg-product/issues/442) flags where appropriate 
- [ ] Include a [X-XSS-Protection: 1; mode=block](https://github.com/18F/cg-product/issues/439) header in responses
- [ ] Include a ["Cache-Control" header with "no-cache, no-store, must-revalidate, private" and "Pragma: no-cache" header](https://github.com/18F/cg-product/issues/441) where appropriate

**Comment by jmcarp** [comment]
We'll get secure cookies once https://github.com/vito/grafana-boshrelease/pull/17 is in.

**Comment by cnelson** [comment]
@jmcarp Looks like that PR was merged, Do we need to do anything else to close this?

**Comment by jmcarp** [comment]
That takes care of the cookie headers--I verified that the `grafana_sess` cookie is using `Secure` and `HttpOnly`. But that work didn't touch the `X-XSS-Protection` or `Cache-Control` headers. I don't see options for setting those in grafana, so I think we're back to using a proxy or submitting patches upstream--or accepting the risk because we're locking grafana down to trusted users (if that's even an option). WDYT?

**Comment by jmcarp** [comment]
Update: filed https://github.com/grafana/grafana/issues/6820, will send a patch there.

**Comment by jmcarp** [comment]
Patch submitted at https://github.com/grafana/grafana/pull/6838. Once the issue is resolved, we'll need to upgrade the grafana bosh release and add relevant variables to the grafana bosh config.
