### ISSUE TITLE
Logsearch should return secure HTTP headers

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#473]
In order to be in compliance with best practice security guidelines I want this application to send the appropriate HTTP headers.

**Acceptance Criteria**
- [x] Cookies should be set with [secure](https://github.com/18F/cg-product/issues/443) and [HttpOnly](https://github.com/18F/cg-product/issues/442) flags where appropriate 
- [x] Include a [X-XSS-Protection: 1; mode=block](https://github.com/18F/cg-product/issues/439) header in responses
- [ ] Include a ["Cache-Control" header with "no-cache, no-store, must-revalidate, private" and "Pragma: no-cache" header](https://github.com/18F/cg-product/issues/441) where appropriate

**Comment by jbarnicle** [comment]
This work has been done.
