### ISSUE TITLE
Change default app domain to `app.cloud.gov` in GovCloud

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-product#499]
We need to create the ELB and the domain in CF. Also the `fr.cloud.gov` domain needs to be set to private and share it with all the people that have it already.

## Tasks

* [ ] Audit apps using `*.fr.cloud.gov` that should be using `*.app.cloud.gov`.
* [ ] Change the domain of any said apps.
* [ ] Update documentation that should be now reference `*.app.cloud.gov` instead of `*.fr.cloud.gov`.

## Acceptance criteria

* [x] `*.app.cloud.gov` points to GovCloud
* [x] `*.app.cloud.gov` is available in all orgs by default as a shared domain
* [x] `*.app.cloud.gov` is the default shared domain used when `push`ing new apps - https://github.com/cloudfoundry/cloud_controller_ng/issues/688#issuecomment-260796291
* [ ] `*.fr.cloud.gov` is not available as a shared domain

**Comment by jbarnicle** [comment]
@dlapiduz Can you update the status on what else needs to be done on this?

**Comment by mogul** [comment]
@afeld and @dlapiduz can you please outline what remains to be done here and/or what blocks this story from progressing?

**Comment by afeld** [comment]
Broke the remaining tasks out to a separate issue: https://github.com/18F/cg-product/issues/541
