### ISSUE TITLE
Document process for creating orgs for internal 18F projects

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#523]
https://cloud.gov/docs/ops/create-org/#non-sandboxes is tailored to external customers...we should determine how we want to structure orgs/quotas for internal 18F projects like Hubot, Dolores, etc.

## Tasks

* [ ] Determine naming convention - @dlapiduz 
* [ ] Document the new convention

## Acceptance criteria

* [ ] 18F projects are organized in a consistent way
* [ ] cloud.gov operators are able to direct 18F projects to the right place to deploy
* [ ] 18F staff know how to request/create a place to deploy
* [ ] As an 18F staff member, I have clear expectations about turnaround time for getting a place to deploy internal projects

**Comment by dlapiduz** [comment]
I think that for this sort of stuff we can use the prototyping org. Its like everyone get one clown car, not more than that :)

I said that we'd put all the bots in the gsa-18f-proto org. What do you think?

**Comment by afeld** [comment]
Why wouldn't we want to separate them into their own orgs?

**Comment by dlapiduz** [comment]
We could do that but it'd create a big sprawl of orgs. If you think we should have separate orgs we can talk about it. I think we will have to setup billing to have 1 IAA -> many orgs anyway

**Comment by suprenant** [comment]
We've been figuring out this process. Let's document if for reference.

**Comment by suprenant** [comment]
We'll talk to [@Britta Gustafson] to outline the path forward here.

**Comment by brittag** [comment]
Yesssss, this is relevant to my interests! When this gets picked up, feel free to put a short meeting on my calendar to talk about it.

**Comment by suprenant** [comment]
@brittag sounds good, thanks!

**Comment by fureigh** [comment]
This has been settled.
