### ISSUE TITLE
Get all brokers maintainable 

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#978]
# What we're after
The brokers we run are getting regular maintenance and we can debug/update them easily.

## Expected benefit(s)/why: 
- Reduce support overhead
- Reduce likelihood of breakage
- Reduce the need for large, disruptive changes
- Reduce the amount of bespoke code we're 100% responsible for

Potential metrics
- The [Component health scorecard](https://docs.google.com/spreadsheets/d/1b-4Qo9xPLdfIfBlJDtKLpbQBdS8LaZMBSUlgZ7IUMRg/edit#gid=0) includes all the brokers, and we're satisfied with their state

---

### Invest
- [ ] custom-domain
- [ ] cdn-route
- [ ] Start using kibosh

### Maintain
- [ ] s3
- [ ] cloud-gov-identity-provider
- [ ] cloud-gov-service-account
- [ ] elasticsearch56
- [ ] elasticsearch24
- [ ] redis32
- [ ] redis28

### Divest
- [ ] aws-rds
- [ ] mongodb36 🌋
