### ISSUE TITLE
Make onboarding checklist filterable for specific responsibilities

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#981]
In order to easily generate incremental checklists that only reflect the minimal tasks a new team member is expected to perform to be ready to tackle a new responsibility in the team, we want a filterable set of onboarding tasks related to particular skills in our [skills map](https://docs.google.com/spreadsheets/d/1ZpIHMPe-fA7qH3CCZA98YdAbCF-EtZHYxPsvYTdnIhU/edit#gid=0)

## Acceptance Criteria
- [ ] WHEN I select a subset of skills in the `onboarding` sheet of the [cloud.gov skills map](https://docs.google.com/spreadsheets/d/1ZpIHMPe-fA7qH3CCZA98YdAbCF-EtZHYxPsvYTdnIhU/edit#gid=0 )
  THEN I see only the related new-starter/buddy tasks related to those skills
  AND I can easily copy-and-paste those tasks into a GitHub issue checklist.

---
## Implementation sketch
- [x] Add Onboarding sheet.
- [x] Enter all the existing onboarding/offboarding tasks and whether it's a mentor/mentee task.
- [ ] Migrate each task from the legacy Onboarding Checklist to a row underneath the competency/skill it relates to.
- [ ] Format every cell under all the people columns as checkboxes for all the filtered "onboarding task" rows.
- [ ] Create a saved filter for each new person reflecting the skills they're onboarding into at the current time (starting with Ben).

**Comment by mogul** [comment]
Previously I said: 
> I'd like to return to this someday, but I don't think I'll be able to before we get a passel of new people joining, so I'm backlogging it.

..but @hillaryj has expressed some interest in taking this back up!
